project:
  type: website
  output-dir: docs

website:
  title: "Dmytro Dushko"
  description: Welcome to my website
  navbar:
    background: "#FFFFFF"
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: work_experience.qmd
        text: "Work experience"
      - href: cv.qmd
        text: "CV"
      - href: contact.qmd
        text: "Contact"
      - href: research_project.qmd
        text: "Research project"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

